(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gra=function(a){a.u||(a.u=new g.$n,g.C(a,a.u));return a.u},H2=function(a){a.R("cardstatechange",g.GL(a)&&g.HL(a)?1:0)},hra=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ck&&a.dataset){if(g.Rc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.ld("pollChoiceIndex"))},ira=function(a){return Math.pow(a,3)},jra=function(a){return 3*a*a-2*a*a*a},I2=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.Mr(c),eventType:4};var d={nk:g.Xr(a),Ai:a};"UNDEFINED_CSN"==a?g.js("visualElementShown",c,d):g.$p("visualElementShown",c,g.Kq,d)})},J2=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Mr(c),eventType:d?16:8};d={nk:g.Xr(a),Ai:a,HE:d};"UNDEFINED_CSN"==a?g.js("visualElementHidden",c,d):g.$p("visualElementHidden",c,g.Kq,d)})},M2=function(a){a=g.Ra(a);
delete K2[a];g.Ob(K2)&&L2&&L2.stop()},lra=function(){L2||(L2=new g.I(function(){kra()},20));
var a=L2;a.isActive()||a.start()},kra=function(){var a=(0,g.H)();
g.Bb(K2,function(b){mra(b,a)});
g.Ob(K2)||lra()},N2=function(a,b,c,d){g.Pn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},mra=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;nra(a,a.progress);1==a.progress?(a.o=0,M2(a),a.xd(),a.A()):1==a.o&&a.At()},nra=function(a,b){g.Oa(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},ora=function(a,b){g.Je.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},O2=function(a,b,c,d,e){N2.call(this,b,c,d,e);
this.element=a},P2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
O2.call(this,a,b,c,d,e)},Q2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},pra=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Ip(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},R2=function(a){return a.baseUrl||null},S2=function(a,b){return(0,g.ve)((0,g.Fc)(a,b,void 0),function(c){return!!c})},qra=function(a,b,c){function d(vb){var Za=vb.hovercardButton;
if(!Za)return null;Za=Za.subscribeButtonRenderer;if(!Za)return null;var xc=f(Za.unsubscribedButtonText),kf=f(Za.subscribedButtonText);if(Za.subscribed){var lf=f(Za.subscriberCountWithUnsubscribeText);var Dh=f(Za.subscriberCountText)}else lf=f(Za.subscriberCountText),Dh=f(Za.subscriberCountWithSubscribeText);var mf=null;return vb.signinEndpoint&&(mf=g.Jb(vb,"signinEndpoint","webNavigationEndpointData","url"),!mf)?null:xc&&(kf||mf)?{subscribed:Za.subscribed,subscribeText:xc,subscribeCount:lf,unsubscribeText:kf,
unsubscribeCount:Dh,enabled:Za.enabled,signinUrl:mf,classic:vb.useClassicSubscribeButton}:null}
function e(vb){if(vb){var Za=[],xc=vb.videoId;xc&&Za.push("v="+xc);(xc=vb.playlistId)&&Za.push("list="+xc);(vb=vb.startTimeSeconds)&&Za.push("t="+vb);return"/watch?"+Za.join("&")}}
function f(vb){if(!vb)return null;var Za=vb.simpleText;return Za?Za:vb.runs?(0,g.Fc)(vb.runs,function(xc){return xc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,B=!1,D=null,E=null,G=null,F=null,ka=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Jb(l,"browseEndpoint","browseId"))z=B,m="/channel/"+z;n=!1;p="new";(B=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.Jb(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(ka=f(b.additionalFeesText)),(n=g.Jb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Jb(b,"title","accessibility","accessibilityData","label");var pa=b.endpoint?b.endpoint.clickTrackingParams:null,bc="";if(b.metadata){var Kc=f(b.metadata);Kc&&(bc=Kc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:bc,callToAction:f(b.callToAction),
Dw:b.image,iconUrl:G,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:E,isSubscribe:B,targetUrl:m,jG:n,Ob:{itct:pa},aP:p,ek:a?a:null,nG:b.isPlaceholder,impressionUrls:S2(b.impressionUrls||[],R2),ZF:S2(b.hovercardShowUrls||[],R2),clickUrls:S2(l.loggingUrls||[],R2),visualElement:g.Lr(b.trackingParams),productPrice:F,
additionalFeesText:ka}},T2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=S2(a.impressionUrls||[],R2);a.trackingParams&&(c.visualElement=g.Lr(a.trackingParams));c.elements=S2(a.elements||[],function(d,e){return qra(b,d,e)});
return c},U2=function(a){g.gM.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.N();this.J=g.Cx(a)||g.Ex(a);this.P=!0;this.G=0;this.B=new g.O(this);g.C(this,this.B);this.B.L(this.player,g.YD("creatorendscreen"),this.aH);this.B.L(this.player,"crx_creatorendscreen",this.bH);this.B.L(this.player,"resize",this.Ry);this.B.L(window,"focus",this.VN);this.load();var b=g.pe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ge(this,function(){g.ue(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},rra=function(a){return a.player.getVideoData().uc?"current":a.J?"new":"current"},V2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},W2=function(a,b,c){c=void 0===c?!0:c;
g.iR(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&sra(a);c=[];d=new g.VD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.w=new g.V({D:"div",I:"ytp-ce-shadow"}),g.RL(a.player,a.w.element,4),a.C=new g.BM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=tra(a,e);a.o[e.id]=f;a.F[e.id]=e;g.RL(a.player,f.element,4);var k=new g.VD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);ura(a,f,e)}g.NL(a.player,c);
a.Ry()}},sra=function(a){var b=g.Ur(),c=g.Wr();
c&&b&&a.u.visualElement&&g.ks(c,b,[a.u.visualElement])},tra=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],M:{tabindex:"0","aria-label":b.ek||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:X2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Y2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.kn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],M:{tabindex:"0","aria-label":b.ek||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:X2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Y2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.kn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],M:{tabindex:"0","aria-label":b.ek||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.kn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)}]};c=new g.V(c);var d=g.be(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Ob.itct}else e="endscreen",f=null;e=new g.yQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],M:{tabindex:"0","aria-label":b.ek||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",M:{dir:g.kn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)},{D:"div",I:"ytp-ce-expanding-icon",M:vra(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],M:{tabindex:"0","aria-label":b.ek||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",M:{dir:g.kn(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.V(c)}b.nG&&g.J(c.element,"ytp-ce-placeholder");return c},X2=function(a){if(a.Dw)var b=a.Dw.thumbnails;
return vra(b?b[b.length-1].url:null)},vra=function(a){return a?{style:"background-image: url("+a+")"}:{}},ura=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ia("mouseenter",(0,g.x)(a.As,a,b,c));b.ia("mouseleave",(0,g.x)(a.Et,a,b,c));a.player.N().o||b.ia("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.x)(a.yA,a,c));b.ia("keypress",(0,g.x)(a.yA,a,c));b.ia("focus",(0,g.x)(function(l,m){this.As(l,m)},a,b,c));
b.ia("blur",(0,g.x)(function(l,m){this.Et(l,m)},a,b,c));
b.ia("touchstart",(0,g.x)(a.As,a,b,c));var f=g.de("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Nn(b.element,"ytp-ce-element-hover");g.Nn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.x)(function(l,m){this.P=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.J(l.element,"ytp-ce-force-expand"),Z2(this,m.id,!0)):(g.Nn(l.element,"ytp-ce-force-expand"),g.Nn(l.element,"ytp-ce-element-hover"),Z2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ia("blur",g.Sa(function(){"none"!=m.style.display&&a.P&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.de("ytp-sb-subscribe",b.element));c(g.de("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},Y2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.ey(c)+b}else return"";return b},Z2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},$2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||V2(a))c&&c();else{b=wra(a,b);var e=0,f=!1,k=new g.I(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Vq(b[a],d)}},a3=function(a,b,c){$2(a,b.clickUrls,c);
(a=g.Wr())&&b.jG&&g.ms(a,b.visualElement)},wra=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(xra(b[e],c));return d},xra=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},yra=function(a){return g.Ma(a)&&a.length?a[0]:a},b3=function(a){return"string"===typeof a?a:""},c3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Ara=function(a){var b=zra;
if(null==a)return null;if(g.Na(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Bra=function(a){this.externalId=a},Cra=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},d3=function(a){if(!a)return null;
var b=g.zc(b3(a.value));b=g.wc(b);if(!b)return null;var c=c3(a.target,Dra,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Cra(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},e3=function(a){return a.value?a.value:null},Era=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},zra=function(a){if(!a)return null;
var b=c3(a.type,Fra),c=c3(a.trigger,Gra),d=yra(a.url);d=d3(d?d:null);a=yra(a.subscribeData);var e=a?a:null;e?(a=b3(e.external_user_id),e=b3(e.subscription_token),a=a&&e?new Bra(a):null):a=null;return b?new Era(b,c,d,a):null},Hra=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Jra=function(a){return(a=Ira(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Ira=function(a,b){return g.$a(a.o,b,void 0)},Kra=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Lra=function(a,b){this.merchant=a;
this.price=b},Mra=function(a){this.o=a},Nra=function(a,b,c){b&&(c?f3(a,(0,g.Fc)(b,g.Sa(function(d,e){return g.hn(e,d)},c))):f3(a,b))},f3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Vq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Ora=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.fb=c;this.videoData=d;this.logger=e;this.aa=f;this.u=k},g3=function(a,b){this.o=a;
this.w=b},Rra=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Pra(b,k))},a);
var d={D:"ul",M:{role:"radiogroup"},K:c},e={};b.Ei&&(e["aria-label"]=g.gN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[h3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Ei&&(f.push("iv-card-unavailable"),d.push({D:"div",X:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",X:["iv-card-sign-in-button","iv-button"],M:{href:e3(b.Ei)},K:[{D:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.V({D:"div",
X:f,K:d});d=f.element;Qra(b,d);pra(a.o.o,d,g.Sa(a.A,b),a);(0,g.y)(g.ce("iv-card-poll-choice-input",d),function(k){this.o.o.ia(k,"focus",g.Sa(this.u,!0));this.o.o.ia(k,"blur",g.Sa(this.u,!1))},a);
b.Ei&&(d=g.de("iv-card-sign-in-button",d),a.w(d,b.Ei,b.id,b.Ob,b.Fc.click,5));return f},Sra=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.uP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.mG&&b.Xv?{D:"span",X:d,M:e,W:b.Xv}:"";c={D:"div",X:["iv-card",c],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Ki,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},j3(a,b)]}]}]};c=new g.V(c);k3(a,g.ce("iv-click-target",c.element),b,b.url);return c},l3=function(a){return a.customMessage?
h3("div","iv-card-message",a.customMessage):""},i3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",M:{style:c},K:d}},j3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(h3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Pra=function(a,b){return{D:"li",
I:Kra(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",M:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},h3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},h3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ma(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.kn(c);return{D:a,M:b,W:c}},Tra=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Vm&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Vm+");");c.dir=g.kn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",X:b,M:c,K:d}},Qra=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.de(Kra(a,e.index),b);e=e.count/c;null==a.Fe&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Fe==d);f.getElementsByTagName("input")[0].checked=a.Fe==d;var k=Math.floor(100*e).toFixed(0),l=g.de("iv-card-poll-choice-percent",f);g.ye(l,g.gN("$PERCENT%",{PERCENT:k}));f=g.de("iv-card-poll-result-bar",f);g.vh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.Fe);g.K(b,"iv-card-poll-expanded",
null!=a.Fe&&1<a.choices.length)},k3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Ob,c.Fc.click,5)},a)},Ura=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Vra=function(a,b){return b?b:Ura(a)?"current":"new"},m3=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.Iu=!1},Wra=function(a,b,c,d,e){var f=e3(b);
if(f){var k=Vra(f,b.target),l=(0,g.x)(function(){b.o&&this.context.aa.pauseVideo();var m=this.context.videoData.uc||!1,n=g.gq(f||"");m&&n&&(n.v||n.list)?g.ST(this.context.aa.app,n.v,c,n.list,!1,void 0):g.kN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);f3(a.context.logger,d,l,e);Ura(f)||(a=g.Wr(),d=c.itct,a&&d&&g.ms(a,g.Lr(d)))}},Xra=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},n3=function(a,b,c){return{Vx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
lC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Ep:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},q3=function(a,b,c){m3.call(this,b,c);
var d=this;this.w=a;this.da=this.Ba=this.C=this.za=!1;this.ea=null;this.Z=new g.I(g.Ja,c.fb.Ra?4E3:3E3);g.C(this,this.Z);this.sa=new g.I(g.Ja);g.C(this,this.sa);this.H=new g3(c,(0,g.x)(this.Oj,this),(0,g.x)(this.eo,this));this.U=new g.V({D:"div",I:"iv-drawer",M:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",M:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],M:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.C(this,this.U);this.F=this.U.element;this.ra=new g.BM(this.U,330);g.C(this,this.ra);this.ya=g.de("iv-drawer-header-text",this.F);this.B=g.de("iv-drawer-content",this.F);this.A=[];this.xa=this.S=this.G=this.ga=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ba&&o3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ba=d.C)&&p3(d)});
this.O=this.J=this.ca=null;this.P=0},Yra=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){o3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){p3(a)});
var c=b.data.headerText;g.ye(a.ya,c);a.S&&a.S.setAttribute("title",c);a.ca=g.Lr(b.data.trackingParams);a.O=g.Lr(b.data.closeTrackingParams);a.J=g.Lr(b.data.iconTrackingParams)},Zra=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.P;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"simple",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:r3(a,c,b,d),sponsored:!1,Fc:n3(d,e,d.command),Zd:d.trackingParams?g.Lr(d.trackingParams):null,Td:e.trackingParams?
g.Lr(e.trackingParams):null,qd:f&&f.trackingParams?g.Lr(f.trackingParams):null,imageUrl:s3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.T(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Vm:null,title:d.title?g.T(d.title):"",customMessage:d.callToAction?g.T(d.callToAction):"",url:d.command.urlEndpoint.url?d3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};t3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"collaborator",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:r3(a,c,b,d),sponsored:!1,Fc:n3(d,e,d.endpoint),Zd:d.trackingParams?g.Lr(d.trackingParams):null,Td:e.trackingParams?g.Lr(e.trackingParams):null,qd:f&&f.trackingParams?
g.Lr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.T(d.customText):null,nB:s3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.T(d.channelName):"",metaInfo:[d.subscriberCountText?g.T(d.subscriberCountText):""],url:d3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};t3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"playlist",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:r3(a,c,b,d),sponsored:!1,Fc:n3(d,e,d.action),Zd:d.trackingParams?g.Lr(d.trackingParams):null,Td:e.trackingParams?g.Lr(e.trackingParams):null,qd:f&&f.trackingParams?g.Lr(f.trackingParams):
null,Ki:s3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.T(d.customMessage):null,playlistVideoCount:g.T(d.playlistVideoCount),title:d.playlistTitle?g.T(d.playlistTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.videoCountText?g.T(d.videoCountText):""],url:d3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Xra(d.action)})};t3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"video",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:r3(a,c,b,d),sponsored:!1,Fc:n3(d,e,d.action),Zd:d.trackingParams?g.Lr(d.trackingParams):null,Td:e.trackingParams?g.Lr(e.trackingParams):null,qd:f&&f.trackingParams?g.Lr(f.trackingParams):null,Ki:s3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.T(d.lengthString):null,customMessage:d.customMessage?g.T(d.customMessage):null,title:d.videoTitle?g.T(d.videoTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.viewCountText?g.T(d.viewCountText):""],isLiveNow:!!d.badge,url:d3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Xra(d.action)})};t3(a,c)}a.P++},s3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},r3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},asa=function(a,b){var c=$ra(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.ue(c.Aq),g.gb(a.A,c),a.Ym(),u3(a))},o3=function(a,b,c){if(!a.C){a.ra.show();
a.ga=new g.I(function(){g.J(g.xL(a.context.aa),"ytp-iv-drawer-open")},0);
a.ga.start();a.ea=g.zp(a.B,"mousewheel",(0,g.x)(a.oH,a));a.C=!0;var d=g.Wr();d&&a.ca&&a.O&&I2(d,[a.ca,a.O]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.Ay||(f.Ay=!0,Nra(a.context.logger,f.card.Fc.Vx,e));d&&I2(d,[f.card.Zd])});
H2(a.w);c&&(a.G=new g.I(function(){a.na=a.S;a.xa.focus()},330),a.G.start())}},p3=function(a){a.C&&(a.ra.hide(),g.Ap(a.ea),a.ea=null,g.Nn(g.xL(a.context.aa),"ytp-iv-drawer-open"),a.C=!1,H2(a.w),a.G&&a.G.stop(),a.G=new g.I(function(){a.na&&(a.na.focus(),a.na=null)},330),a.G.start())},bsa=function(a){var b=g.de("iv-drawer-close-button",a.F);
a.context.o.ia(b,"click",a.pE,a);a.context.o.ia(a.B,"touchend",function(){a.Z.start()});
a.context.o.ia(a.B,"scroll",a.DE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.Ln(g.xL(a.w),"ytp-autohide")});
a.V.push(g.So("iv-button-shown",a.uG,a));a.V.push(g.So("iv-button-hidden",a.tG,a));a.V.push(g.So("iv-teaser-shown",a.xG,a));a.V.push(g.So("iv-teaser-hidden",a.wG,a));a.V.push(g.So("iv-teaser-clicked",a.vG,a))},t3=function(a,b){a.za||(g.Mn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.RL(a.w,a.F,5),bsa(a),a.S=g.de("ytp-cards-button",g.xL(a.w)),a.xa=g.de("iv-drawer-close-button",a.F),a.za=!0);asa(a,b.id);var c=csa(a,b);if(c){var d={card:b,Aq:c.element,Ay:!1},e=dsa(a,d);g.ob(a.A,e,0,d);c.ba(a.B,e);a.Ym();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.KO,d)):(c=1E3*a.context.aa.getCurrentTime(),5E3>c&&c>b.startMs&&a.RB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.RB,d)),u3(a))}},csa=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=Tra(b);d={D:"div",X:["iv-card"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[h3("h2",void 0,b.title),e]}]}]};d=new g.V(d);k3(c,g.ce("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],M:{href:e3(b.url),"data-ytid":b.channelId},K:[i3(b.nB),{D:"div",I:"iv-card-content",
K:[l3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},j3(c,b)]}]}]},d=new g.V(d),k3(c,g.ce("iv-click-target",d.element),b,b.url),d;case "episode":return Sra(a.H,b,"iv-card-episode");case "movie":return Sra(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Ki,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[l3(b),
h3("h2","iv-card-primary-link",b.title),j3(c,b)]}]}]},d=new g.V(d),k3(c,g.ce("iv-click-target",d.element),b,b.url),d;case "poll":return Rra(a.H,b);case "productListing":c=a.H;var f=!g.db(b.offers);d=["iv-card"];e="";var k=Tra(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",X:d,M:{tabindex:"0"},K:[{D:"a",
X:["iv-card-image","iv-click-target"],M:{style:"background-image: url("+b.imageUrl+");",href:e3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[h3("h2",e,b.title),k]}]}]};d=new g.V(d);
e=g.pe("span");g.ye(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ub(e,"adInfo");k3(c,g.ce("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Ki,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[l3(b),h3("h2","iv-card-primary-link",b.title),j3(c,b),d]}]}]},d=new g.V(d),k3(c,g.ce("iv-click-target",d.element),b,b.url),d}return null},dsa=function(a,b){if(0==a.A.length)return 0;
var c=g.ab(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},esa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.vi)(a.A,function(b){return"productListing"==b.card.type})},u3=function(a){g.K(g.xL(a.w),"ytp-cards-shopping-active",esa(a))},fsa=function(a,b){if(a.U.Ea()){var c=new N2([0,
a.B.scrollTop],[0,b.Aq.offsetTop],600,jra);a.context.w.ia(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ia(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.HC(a.U,!0),a.B.scrollTop=b.Aq.offsetTop,g.HC(a.U,!1)},v3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},$ra=function(a,b){return g.$a(a.A,function(c){return c.card.id==b})},w3=function(a,b,c){m3.call(this,a,b);
this.annotation=c;this.isActive=!1},gsa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x3=function(a,b,c){w3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},y3=function(a,b,c){w3.call(this,a,b,c);
this.J=this.C=this.P=!1;this.G=5E3;this.B=null;this.H=g.oe("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.I(function(){this.u.setAttribute("aria-hidden",!0);g.Qh(this.A,!1);g.Qh(this.w,!0)},700,this);
g.C(this,this.F)},hsa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=Jra(a.annotation),f=b.image_url;if(f){var k=g.oe("DIV",["iv-promo-img","iv-click-target"]);f=g.oe("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.oe("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.oe("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Oj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.oe("A","iv-promo-txt"),g.ad(f,e3(e)),a.u=f):a.u=g.oe("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.oe("P",null,g.oe("STRONG",null,b.text_line_1));var m=g.oe("P",null,g.oe("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.Q(a.context.fb.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.oe("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.oe("BUTTON",["iv-button","iv-promo-button"],g.oe("SPAN","iv-button-content",f));var p=g.oe("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Oj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.J(a.u,"iv-click-target");e&&a.Oj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.oe("P",null,g.oe("SPAN",null,b.text_line_1)),
m=g.oe("P",null,g.oe("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.oe("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.u,"iv-click-target"),e&&a.Oj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);p&&a.H.appendChild(p);c=g.oe("DIV","iv-promo-actions");a.w=g.oe("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ia(a.w,"click",g.Sa(a.yr,5E3),a);c.appendChild(a.w);g.Qh(a.w,!1);
a.context.o.ia(a.o,"mouseover",a.CF,a);a.context.o.ia(a.o,"mouseout",a.BF,a);a.context.o.ia(a.o,"touchend",g.Sa(a.yr,5E3),a);a.A=g.oe("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ia(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.uF:a.tF,a);c.appendChild(a.A);g.Mn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},isa=function(a){a.C||a.J||a.B||(g.J(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},jsa=function(a){a.F.stop();
a.C&&(g.On(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Qh(a.w,!1),g.Qh(a.A,!0))},ksa=function(a,b){a.B||(a.B=g.Wf(function(){z3(this);
isa(this)},b,a))},z3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},A3=function(a){g.gM.call(this,a);
this.J=!1;this.H=0;this.F={};this.U=new Mra(a);this.B=new g.O(this);g.C(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.tM,this);this.subscribe("resize",this.Xo,this);this.player.N().F.subscribe("vast_info_card_add",this.ZA,this);this.S=new g.O(this);g.C(this,this.S);this.O=g.oe("DIV","video-custom-annotations");this.u=new g.V({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.RL(this.player,this.u.element,4);this.u.hide();this.A=new g.V({D:"div",X:["ytp-iv-video-content"]});g.C(this,this.A);g.re(this.A.element,g.oe("DIV","video-annotations",
this.O));this.G=this.o=null;this.P=[];lsa(this)&&this.load();var b=g.pe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ge(this,function(){g.ue(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},msa=function(){var a=g.oe("DIV",["annotation",
"annotation-type-custom"]);g.Qh(a,!1);return a},nsa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},lsa=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.NC||b.F.get(a.videoId)||g.PB(a)||g.QB(a)?!0:!1},osa=function(a,b,c){a.J=!0;
a.C=g.yq(b,c)},psa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(psa(a,e))}return c},qsa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},tsa=function(a){var b=a.player.getVideoData();
if(b.Yd){var c=a.player.N().F.get(b.videoId);if(c){var d={format:"XML",Xd:{},method:"POST",withCredentials:!0};d.xd=(0,g.x)(function(e,f,k){qsa(this,e,f)||(e=g.sq(k)&&k.responseXML?k.responseXML:null)&&B3(this,e)},a,a.H,b.videoId);
g.Qp()&&(d.xd=rsa(a,d.xd));d.zb={ic_only:"1"};ssa(d,c);a.J=!0;g.yq(b.Yd,d)}}},ssa=function(a,b){a.method="POST";
a.zb=a.zb||{};b.cn&&(a.zb.ic_coll=b.cn);b.dn&&(a.zb.ic_xml=b.dn);b.pm&&(a.zb.ic_track=b.pm)},usa=function(a){var b=new g.V({D:"div"});
g.Qh(b.element,!1);var c=new q3(a.player,b.element,C3(a));g.C(c,b);b.ba(a.u.element);c.dm();return c},C3=function(a){if(!a.G){var b=new Q2(a);
g.C(a,b);var c=new g.R1(a);g.C(a,c);a.G=new Ora(b,c,a.player.N(),a.player.getVideoData(),a.U,a.player,a.lc)}return a.G},B3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Wr();if(e){var f=g.Ur();f&&g.ks(e,f,[g.Lr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=psa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=c3(k.type,vsa),t=c3(k.style,wsa),u=b3(k.data),z=0!=u.length?JSON.parse(u):{},B=Ara(k.action);f=n&&p?new Hra(n,p,t,B,z):null}else f=null}catch(ka){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=msa(),E=null;switch(m.type){case "branding":if(k.player.N().Na)break;k.u.element.appendChild(D);E=new x3(D,C3(k),m);break;case "promotion":g.RL(k.player,D,4),E=new y3(D,C3(k),m)}E&&E.dm();if(k=E)g.C(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=usa(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Vx:k.impression,click:k.click,close:k.close,lC:k.teaser_impression,Ep:k.teaser_click},m=f.data.tracking_params||
{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,nB:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):
null,Ki:f.data.image_url,Xv:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,mG:!!f.data.is_paygated,uP:!!f.data.user_has_entitlement,url:d3({target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):null,Ki:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):null,title:f.data.title,choices:f.data.choices,Fe:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Ei:f.data.signin_url?d3({target:"current",value:f.data.signin_url}):null,FP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};t3(c,f);break;case "productListing":f.data.signin_url&&(D=d3({target:"current",
value:f.data.signin_url}));E=[];for(var G=f.data.offers||[],F=0;F<G.length;F++)E.push(new Lra(g.hd(G[F].merchant),g.hd(G[F].price)));f={JT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Vm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Ei:D,bU:f.data.signin_title?f.data.signin_title:null,aU:f.data.signin_message?f.data.signin_message:null,offers:E};t3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):null,qd:m.icon?g.Lr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Vm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Fc:k,Zd:m.card?g.Lr(m.card):null,Td:m.teaser?g.Lr(m.teaser):
null,qd:m.icon?g.Lr(m.icon):null,Ki:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},t3(c,f)}}else Yra(a.o,f);c=!0}}}c&&(H2(a.player),a.Xo())},xsa=function(a,b){var c=!1;
a.o||(a.o=usa(a),g.C(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())Zra(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.T(b.headerText):"",g.ye(c.ya,d),c.S&&c.S.setAttribute("title",d),c.ca=b.trackingParams?g.Lr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Lr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Lr(b.icon.infoCardIconRenderer.trackingParams):null,H2(a.player),a.Xo())},
ysa=function(a,b,c,d,e){if(!a.player.N().Na){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Era("openUrl","click",new Cra("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.T(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.T(b.subscriberCountText))):(b.subscriberCountText&&(e=g.T(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.T(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.T(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.T(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Hra(c,"branding","branding",f,d);d=msa();a.u.element.appendChild(d);f=new x3(d,C3(a),f);f.dm();g.C(f,f);a.F[c]=f}},rsa=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.P.push(g.Op(b))}},a)},K2={},L2=null;g.Ua(N2,g.Pn);g.h=N2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;M2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.te("play");-1==this.o&&this.te("resume");this.o=1;var b=g.Ra(this);b in K2||(K2[b]=this);lra();mra(this,a);return!0};
g.h.stop=function(a){M2(this);this.o=0;a&&(this.progress=1);nra(this,this.progress);this.te("stop");this.A()};
g.h.pause=function(){1==this.o&&(M2(this),this.o=-1,this.te("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.te("destroy");N2.Gb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.At=function(){this.te("animate")};
g.h.te=function(a){this.dispatchEvent(new ora(a,this))};
g.Ua(ora,g.Je);g.Ua(O2,N2);O2.prototype.C=g.Ja;O2.prototype.At=function(){this.C();O2.Gb.At.call(this)};
O2.prototype.A=function(){this.C();O2.Gb.A.call(this)};
O2.prototype.B=function(){this.C();O2.Gb.B.call(this)};
g.Ua(P2,O2);P2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(Q2,g.A);Q2.prototype.ia=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.zp(a,b,c);this.o.push(a);return a};
Q2.prototype.gs=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Jp(a,b,c);this.o.push(a);return a};
Q2.prototype.Xa=function(a){g.Ap(a);g.gb(this.o,a)};
Q2.prototype.Y=function(){g.Ap(this.o);this.o.length=0;g.A.prototype.Y.call(this)};g.r(U2,g.gM);g.h=U2.prototype;g.h.load=function(){g.gM.prototype.load.call(this);if(!V2(this)){var a=g.OB(this.player.getVideoData());if(a)a=T2(a,rra(this)),W2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",xd:(0,g.x)(this.fL,this,a),Xd:{v:a},withCredentials:!0};this.J&&(a.Xd.ptype="embedded");var c=this.player.getVideoData().qn;c&&(a.zb={ad_tracking:c});if(b=g.NB(b))if(b=g.zc(b),b=g.wc(b))this.A=g.yq(b,a)}}};
g.h.unload=function(){W2(this,null);this.A&&(this.A.abort(),this.A=null);g.gM.prototype.unload.call(this)};
g.h.Lc=function(a,b){if(!V2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=T2(b,"new");W2(this,c);return!0}return null};
g.h.getOptions=function(){return V2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.fL=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=T2(c,rra(this)))}W2(this,c)};
g.h.Ry=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<zsa.length;f++){var k=Math.abs(b.width-zsa[f]);if(-1==e||d>=k)e=f,d=k}d=Asa[e];this.w&&g.vh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Oh(e.element,Math.round(k.width*a.width),f);g.Eh(e.element,m,n);g.On(e.element,Bsa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.On(e.element,Asa);g.J(e.element,d);(e=g.be(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.vh(e,"height",f+"px")}}}}};
g.h.aH=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())$2(this,this.u.impressionUrls),(a=g.Wr())&&this.u.visualElement&&g.ls(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.J(g.xL(this.player),"ytp-ce-shown");$2(this,c.impressionUrls);(b=g.Wr())&&g.ls(b,c.visualElement);this.player.N().Eb&&this.player.ma("endscreenelementshown",a)}};
g.h.bH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Nn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.Nn(g.xL(this.player),"ytp-ce-shown");this.player.N().Eb&&this.player.ma("endscreenelementhidden",a)}};
g.h.VN=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c in b.o)g.On(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.yA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Ln(c,"ytp-ce-element");){g.Ln(c,"subscribe-label")&&a3(this,a);if(g.Ln(c,"ytp-ce-channel-subscribe"))return;c=g.we(c)}if(!c||g.Ln(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Et(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.aP?(a3(this,a),this.QB(),this.player.pauseVideo(),c=g.zc(Y2(this,a.targetUrl)),c=g.wc(c),g.kN(c,void 0,a.Ob)):(c=this.player.getVideoData().uc,
c=(0,g.x)(this.TO,this,c,Y2(this,a.targetUrl),a.Ob),c=(0,g.x)(this.QB,this,c),a3(this,a,c))}}};
g.h.TO=function(a,b,c){var d=g.gq(b);a&&d&&(d.v||d.list)?g.ST(this.player.app,d.v,c,d.list,!1,void 0):g.jN(b,c)};
g.h.As=function(a,b){g.Ln(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.I(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),$2(this,b.ZF),Z2(this,b.id,!0))};
g.h.Et=function(a,b){g.Nn(a.element,"ytp-ce-element-hover");g.Nn(a.element,"ytp-ce-force-expand");Z2(this,b.id,!1)};
g.h.QB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var zsa=[346,426,470,506,570,640,853,1280,1920],Asa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Bsa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Dra={LQ:"current",gS:"new"};var Fra={CLOSE:"close",jS:"openUrl",JD:"subscribe"},Gra={FQ:"click",CLOSE:"close",wR:"hidden",OS:"rollOut",PS:"rollOver",SS:"shown"};var wsa={iQ:"anchored",dD:"branding",CHANNEL:"channel",KQ:"cta",yR:"highlightText",PR:"label",PLAYLIST:"playlist",BS:"popup",XS:"speech",JD:"subscribe",hT:"title",VIDEO:"video",uT:"website"},vsa={dD:"branding",wQ:"card",RQ:"drawer",xR:"highlight",WR:"marker",GS:"promotion",TEXT:"text",wT:"widget"};g3.prototype.u=function(a,b){var c=g.De(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
g3.prototype.A=function(a,b){var c=g.De(b.target,null,"iv-card-poll",void 0);if(c)if(a.Ei)g.de("iv-card-sign-in-button",c).click();else{var d=parseInt(hra(b.target),10);if(null==a.Fe)a.choices[d].count++,a.Fe=d;else if(a.Fe!=d){var e=a.choices[a.Fe];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Fe=d}else e=a.choices[a.Fe],e.count=Math.max(e.count-1,0),a.Fe=null;Qra(a,c);g.Cq(this.o.videoData.Yd,{Xd:{action_poll_vote:1},zb:{poll_id:a.id,index:d,session_token:a.FP}});f3(this.o.logger,a.Fc.click,
void 0,5);(c=g.Wr())&&a.Zd&&g.ms(c,a.Zd)}};g.r(m3,g.A);g.h=m3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.VD(a,b,{id:c});g.C(this,a);a.namespace="annotations_module";d&&gra(a).subscribe("onEnter",d,this);e&&gra(a).subscribe("onExit",e,this);g.NL(this.context.aa,[a])};
g.h.dm=function(){this.context.u.subscribe("resize",this.Ym,this)};
g.h.Oj=function(a,b,c,d,e,f){this.context.o.ia(a,"click",g.Sa(this.eo,b,c,d,e||[],f||0),this);this.context.o.ia(a,"touchstart",g.Sa(function(){this.Iu=!1}),this);
this.context.o.ia(a,"touchmove",g.Sa(function(){this.Iu=!0}),this)};
g.h.eo=function(a,b,c,d,e,f){if(this.Iu)return!1;f&&(f.stopPropagation(),f.preventDefault());Wra(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.ue(this.o)};
g.h.Ym=function(){};g.r(q3,m3);g.h=q3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.xL(this.w))?(a=g.Ph(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Ym=function(){var a=this.isAvailable();g.Qh(this.o,a);g.K(g.xL(this.context.aa),"ytp-iv-drawer-enabled",a);H2(this.w)};
g.h.destroy=function(){var a=g.FL(g.sL(this.w));a&&a.ws(!1,void 0);try{g.xL(this.w).removeChild(this.F)}catch(b){}g.To(this.V);g.Ap(this.ea);this.ga&&this.ga.dispose();this.G&&this.G.dispose();m3.prototype.destroy.call(this)};
g.h.oH=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.RB=function(a){if(!g.Ln(g.xL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Wr(),c=this.u?this.u.card.qd:this.J;b&&c&&J2(b,[c]);this.u=a;u3(this)}if(b="none"!=this.o.style.display)2==this.context.aa.getPresentingPlayerType()?b=1==this.context.aa.getAdState():(b=this.context.aa.getPlayerState(),c=0==b&&0===this.context.aa.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.FL(g.sL(this.w)))&&c.ws(!0,b));
this.sa.isActive()||((!this.C||!this.Z.isActive()&&this.da)&&fsa(this,a),this.sa.start(910+a.card.teaserDurationMs))}};
g.h.KO=function(a){this.C||(this.u=a,u3(this),fsa(this,a),o3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.pE=function(){if(this.C){f3(this.context.logger,v3(this).Fc.close);var a=g.Wr();a&&this.O&&g.ms(a,this.O);p3(this)}};
g.h.DE=function(){g.K(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.uG=function(){var a=g.Wr(),b=v3(this);b=b?b.qd:this.J;a&&b&&I2(a,[b])};
g.h.tG=function(){var a=g.Wr(),b=v3(this);b=b?b.qd:this.J;a&&b&&J2(a,[b])};
g.h.xG=function(){var a=v3(this);f3(this.context.logger,a.Fc.lC);var b=g.Wr();b&&a&&I2(b,[a.Td,a.qd])};
g.h.wG=function(){var a=g.Wr(),b=v3(this);a&&b&&J2(a,[b.Td])};
g.h.vG=function(a){var b=v3(this),c=g.Wr();this.u?a?(a=this.context.logger,f3(a,b.Fc.Ep),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.ms(c,b.Td)):(a=this.context.logger,f3(a,b.Fc.Ep),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.qd&&g.ms(c,b.qd)):(a=this.context.logger,f3(a,b.Fc.Ep),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.ms(c,this.J))};g.r(w3,m3);w3.prototype.dm=function(){m3.prototype.dm.call(this);gsa(this)};
w3.prototype.show=function(){m3.prototype.show.call(this);var a=g.Wr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&I2(a,[g.Lr(b.itct)])};
w3.prototype.hide=function(){m3.prototype.hide.call(this);var a=g.Wr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&J2(a,[g.Lr(b.itct)])};g.r(x3,w3);g.h=x3.prototype;g.h.UO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Ph(a);this.u||(g.Nh(a,e.width),g.Nh(b,e.width));g.vh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.vh(c,"right","1px");this.B=!0;g.Qh(a,!0);this.C=new g.I(function(){g.J(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.YF=function(a,b){g.Nn(this.o,"iv-branding-active");this.F=new g.I((0,g.x)(function(){g.Qh(a,!1);this.u||g.Nh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){w3.prototype.show.call(this);if(!this.G){g.J(this.o,"iv-branding");var a=this.annotation.data;this.w=g.oe("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Qh(this.w,!1);var b=g.oe("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=Jra(this.annotation))&&this.Oj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.oe("DIV","iv-branding-context-name");
g.ye(c,a.channel_name);var d=g.oe("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.yQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.aa),this.u.ba(d);b=g.oe("DIV","iv-branding-context-subscribe-caret");c=g.oe("DIV","branding-context-container-inner",b,c,d);g.Qh(c,!1);d=g.oe("DIV","branding-context-container-outer",c);g.vh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.I(g.Sa(this.YF,c,d),500,this);g.C(this,this.A);this.context.o.ia(this.o,"mouseover",(0,g.x)(this.UO,this,c,d,b,a.image_height));this.context.o.ia(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Qh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Ih(a);c=g.Ph(a);b=(new g.sh(b.x,b.y,c.width,c.height)).width;g.Eh(a,b);e=new P2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,ira);g.C(this,e);this.context.w.ia(e,
"begin",g.Sa(g.Qh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(w3.prototype.hide.call(this),g.Qh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);w3.prototype.destroy.call(this)};g.r(y3,w3);g.h=y3.prototype;g.h.show=function(){this.isActive||(w3.prototype.show.call(this),this.P||(hsa(this),this.P=!0),g.Qh(this.o,!0),g.Wf(function(){g.Nn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,z3(this),jsa(this),ksa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.J(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.eo=function(a,b,c,d,e,f){return this.C?!1:w3.prototype.eo.call(this,a,b,c,d,e,f)};
g.h.yr=function(a,b){b.stopPropagation();jsa(this);ksa(this,a);this.u.focus()};
g.h.CF=function(a){this.J=!0;this.yr(500,a)};
g.h.BF=function(){this.J=!1;isa(this)};
g.h.tF=function(a){a.stopPropagation();this.hide()};
g.h.uF=function(a){a.stopPropagation();z3(this);this.C=!0;g.J(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();w3.prototype.destroy.call(this)};g.r(A3,g.gM);g.h=A3.prototype;g.h.Lc=function(a,b){if(!nsa(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Q1(b);c&&B3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(asa(this.o,b),H2(this.player)),!0}return null};
g.h.getOptions=function(){return nsa(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Xo=function(){if(this.A){var a=g.wL(this.player).getVideoContentRect(!0);g.Oh(this.A.element,a.width,a.height);g.Eh(this.A.element,a.left,a.top)}if(this.o){var b=g.IL(this.player);a=this.o;b=b.width;g.K(a.F,"iv-drawer-small",426>=b);g.K(a.F,"iv-drawer-big",1280<=b)}};
g.h.tM=function(a){this.pc(a.state);g.W(a.state,2)&&(this.ql()&&this.Hy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ws(!1))};
g.h.load=function(){g.gM.prototype.load.call(this);this.pc(g.zL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.hL,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Qp()&&(c=rsa(this,c));c={format:"XML",xd:c,onError:d,Xd:{}};a.isPharma&&(c.Xd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.N().F.get(b))&&ssa(c,b);b=b&&(b.dn||b.cn);if(!a.Pm||b)a.Yd?osa(this,a.Yd,c):(this.w=(0,g.x)(this.YG,this,c),this.player.addEventListener("videodatachange",this.w));g.RL(this.player,this.A.element,4);this.Xo();(b=g.PB(a))&&xsa(this,b);(b=g.QB(a))&&b.featuredChannel&&ysa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.pc=function(a){a=!a.isCued()&&!g.W(a,1024);g.HC(this.u,a);g.HC(this.A,a)};
g.h.YG=function(a){var b=this.player.getVideoData();b.Yd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),osa(this,b.Yd,a))};
g.h.unload=function(){g.iR(this.player.app,"annotations_module",void 0);g.Bb(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,H2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.gM.prototype.unload.call(this);g.EC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.hL=function(a,b,c){this.C=null;!qsa(this,b,a)&&(a=g.sq(c)&&c.responseXML?c.responseXML:null)&&(B3(this,a),g.J(g.xL(this.player),"iv-module-loaded"))};
g.h.ZA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?tsa(this):this.load())};
g.h.ql=function(){return!!this.o&&this.o.isAvailable()};
g.h.Hy=function(){this.ql();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ql();this.o&&(a?c?o3(this.o,c,b):o3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):p3(this.o))};
g.h.ws=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.N().F.unsubscribe("vast_info_card_add",this.ZA,this);g.Nn(g.xL(this.player),"ytp-iv-drawer-open");for(var a=this.P,b=0,c=a.length;b<c;b++)g.Rp(a[b]);this.P.length=0;g.gM.prototype.Y.call(this)};g.vM.annotations_module=A3;g.vM.creatorendscreen=U2;})(_yt_player);
