(function(g){var window=this;var G3=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.rz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.F,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},H3=function(a){return a.o?a.o.languageCode:a.u},Csa=function(a,b){var c=new g.qz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},Dsa=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];
if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var k=a[c++],l=a[c++];e=((e&7)<<18|(f&63)<<12|(k&63)<<6|l&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],k=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|k&63)}return b.join("")},Esa=function(){this.u=[];
this.o=[]},I3=function(a,b){return b?a.o.concat(a.u):a.o},J3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.$a(c,(0,g.x)(b.Bs,b))||c.push(b);break;default:c=a.o,g.$a(c,(0,g.x)(b.Bs,b))||c.push(b)}},K3=function(a){g.A.call(this);
this.fb=a;this.u=new Esa;this.B=[]},L3=function(a,b,c){K3.call(this,a);
this.o=null;this.B=b.ew;this.w=c},M3=function(){this.segments=[]},N3=function(a,b,c,d,e,f){g.A.call(this);
this.J=a;this.w=b;this.O=b.N();this.B=new M3;this.o=null;this.F=d;this.P=f;this.u=this.A=null;this.S=c;this.C=e||!1;this.G=new g.I(this.yy,1E3,this);g.C(this,this.G);this.H=new g.O(this);g.C(this,this.H);this.H.L(b,"SEEK_COMPLETE",this.rz);this.rz();this.yy()},Fsa=function(a,b){b-=a.w.Bb();
var c=a.o;a.o=g.Xa(a.S.Yf(b).o);c!=a.o&&a.P&&a.P()},Gsa=function(a,b){var c=g.mv(g.qy(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.ar(c,d,3,100).then((0,g.x)(a.PM,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.rb(c.segments,d);0<=e||0>e&&1===(-e-1)%2||(e=-e-1,0<e&&1===d-c.segments[e-1]&&e<c.segments.length&&1===c.segments[e]-d?(g.fb(c.segments,e),g.fb(c.segments,e-1)):0<e&&1===d-c.segments[e-1]?c.segments[e-1]=d:e<c.segments.length&&1===c.segments[e]-d?c.segments[e]=d:(g.ob(c.segments,e,0,d),g.ob(c.segments,e+1,0,d)))},O3=function(a,b){K3.call(this,b.N());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.Wx(this.F.N())&&!this.o.u},Hsa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.hM(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.qz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Isa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},Jsa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.hM(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},P3=function(a,b,c,d,e){K3.call(this,e||null);
c=c||g.gq(a).hl||"";c=c.split("_").join("-");this.A=g.iq(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},Q3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.VD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},R3=function(a,b,c,d,e){g.VD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},S3=function(a,b){g.C(a,b);
a.o.push(b)},Ksa=function(a){a=void 0===a?{}:a;
var b="_"+T3++;return new R3(0,0x8000000000000,0,b,a)},U3=function(a,b,c,d,e,f){var k={};
g.Ta(k,b);g.Ta(k,a.params);g.Ta(k,c);var l={};g.Ta(l,b.Db);a.params.Db&&g.Ta(l,a.params.Db);g.Ta(l,c.Db);k.Db=l;g.V.call(this,{D:"div",I:"caption-window",M:{id:"caption-window-"+a.id,dir:1==k.Ud?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{D:"span",I:"captions-text",M:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.S=!1;this.w=a;this.V=this.U=null;this.Ja=e;this.Ha=f;this.F=null;this.ca=.96*e;this.xa=.96*f;this.u=k;this.Fa=c;this.B=this.o["captions-text"];this.za=
null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ga=this.Z*Lsa(l);a=new g.Dr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.vI,this);a.subscribe("dragmove",this.uI,this);a.subscribe("dragend",this.tI,this);this.sa=this.na=0;b="";this.u.windowOpacity&&(a=g.P1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":Msa[this.u.textAlign]};
this.za&&(a["border-radius"]=b?this.ga/8+"px":"");if(this.A=2==this.w.params.Ud||3==this.w.params.Ud)b=this.element,c="vertical-rl",1==this.u.ru&&(c="vertical-lr"),g.ie&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.vh(b,"-o-writing-mode",c),g.vh(b,"-webkit-writing-mode",c),g.vh(b,"writing-mode",c),g.vh(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.w.params.Ud&&(g.vh(b,"text-orientation",""),g.vh(b,"transform","rotate(180deg)"));g.vh(this.element,a);switch(this.u.Nf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},Lsa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Nsa=function(a,b){var c={},d=b.background?b.background:a.u.Db.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Db.backgroundOpacity;d=g.P1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.za&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*Lsa(b)+"px";d=1;e=b.color||a.u.Db.color;if(b.color||null!=b.textOpacity)e=g.P1(e),d=null==b.textOpacity?a.u.Db.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Cq&&(k=e=b.Cq);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.il()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Db.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Te&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.XF&&(c.visibility="hidden");1==b.Sx&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Zx||g.$x,3==a.w.params.Ud?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.af||2==b.af||3==b.af||4==b.af||5==b.af)if(g.Zx)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.af){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Osa=function(a){a.F=g.pe("SPAN");
g.vh(a.F,{display:"block"});g.J(a.F,"caption-visual-line");a.B.appendChild(a.F)},Psa=function(a,b){var c=g.pe("SPAN");
g.vh(c,{display:"inline-block","white-space":"pre-wrap"});g.vh(c,Nsa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.vh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.vh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Qsa=function(a,b,c){a.S=a.S||!!c;
var d={};g.Ta(d,a.u.Db);g.Ta(d,c||b.o);g.Ta(d,a.Fa.Db);(c=!a.F)&&Osa(a);for(var e=a.U&&a.V&&g.Qb(d,a.V)?a.U:Psa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(Osa(a),e=Psa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.qe(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Zx||!g.zh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.zh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.ke?g.vh(e,m,"1em"):g.vh(e,m,"0.5em")))}a.V=d;a.U=e;a.C.push(b)},Rsa=function(){},W3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new V3(this);this.C=new V3(this);this.o=[];this.clear()},Tsa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Rm:a,
Sm:b,result:0};a=Ssa[a];b=Ssa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{Rm:a,Sm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Rm:a,Sm:b,result:2};return{Rm:a,Sm:b,result:3}},Vsa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Usa(a.B,b,c,d))},Wsa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Vsa(a,d.hw,d.iw,b):1==d.type&&a.w&496&&Usa(a.C,d.hw,d.iw,b)}a.o.length=0},X3=function(){this.o=0},Y3=function(){this.u=this.w=this.o=0},Z3=function(){this.timestamp=this.pe=0},$3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new Z3}this.o=this.u=this.row=0;this.style=new X3;this.B=a;this.A=0},a4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.w[m][p];
if(0!=t.pe){0==c&&(c=m,d=p);n=String.fromCharCode(t.pe);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.pe||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.w[k][m],t=p.pe,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},ata=function(a,b){switch(a){case 0:return Xsa[(b&127)-32];
case 1:return Ysa[b&15];case 2:return Zsa[b&31];case 3:return $sa[b&31]}return 0},b4=function(a){return a.w[a.row][a.u]},c4=function(a,b,c){2<=b&&1<a.u&&(--a.u,b4(a).pe=0);
var d=b4(a);d.timestamp=a.B.u+0;d.pe=ata(b,c);32>a.u&&a.u++},bta=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].Mg(a.w[c+e][f])},d4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},e4=function(a){a.row=0<a.o?a.o:1;
a.u=1;d4(a,0,15)},f4=function(a){this.A=a;
this.B=0;this.style=new X3;this.C=new $3(a);this.F=new $3(a);this.G=new $3(a);this.u=this.C;this.w=this.F;this.o=this.u},g4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:a4(d,c),e4(a.u),e4(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(a4(d,c),d4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},cta=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},dta=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},V3=function(a){this.u=a;
this.o=new Y3;this.B=0;this.w=new f4(a);this.C=new f4(a);this.A=this.w},Usa=function(a,b,c,d){a.o.update();
b=Tsa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Rm;c=b.Sm;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&c4(a,0,b),c&96&&c4(a,0,c),0!=b&&0!=c&&3==a.style.o&&a4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;bta(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));d4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:c4(b.o,0,32);break a;case 48:57==c?(d=b.o,b4(d).pe=0,32>d.u&&d.u++):c4(b.o,1,c&15)}break;case 2:c&32&&c4(b.o,2,c&31);break;case 3:c&32&&c4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:cta(b);break;
case 33:d=b.o;1<d.u&&(--d.u,b4(d).pe=0);break;case 36:d=b.o;b=b4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:g4(b,2,d);break;case 38:g4(b,3,d);break;case 39:g4(b,4,d);break;case 40:c4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);e4(d);dta(b);break;case 43:dta(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:a4(a,d)}d4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;a4(a,d);bta(a,b,b+1,a.o-1);d4(a,a.row,1)}break;case 46:d4(b.w,0,15);break;case 47:a4(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,cta(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},fta=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Nb){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=eta(l.textContent,n.textContent,p.textContent,f.textContent,k);return new Q3(a,b,e,c,l,d,m)}switch(m.Nb){case 9:case 10:m.af=1;break;case 11:m.af=2;break;case 12:m.af=3;break;case 13:m.af=4;break;case 14:m.af=5}return new Q3(a,b,e,c,l.textContent||"",d,m)},eta=function(a,b,c,d,e){var f=g.il(),k=f?
g.pe("DIV"):g.pe("RUBY"),l=g.pe("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.pe("DIV"):g.pe("RP");a.textContent=b;k.appendChild(a);b=f?g.pe("DIV"):g.pe("RT");b.textContent=c;k.appendChild(b);c=e.Nb;if(10==c||11==c||12==c||13==c||14==c)if(g.vh(b,"text-emphasis-style","filled circle"),g.vh(b,"text-emphasis-color","currentcolor"),g.vh(b,"webkit-text-emphasis","filled circle"),e.Nb==e.Nb==11||13==e.Nb)g.vh(b,"webkit-text-emphasis-position","under left"),g.vh(b,"text-emphasis-position","under left");c=!0;if(4==e.Nb||7==e.Nb||12==e.Nb||14==
e.Nb)g.vh(k,"ruby-position","over"),g.vh(k,"-webkit-ruby-position","before");else if(5==e.Nb||6==e.Nb||11==e.Nb||13==e.Nb)g.vh(k,"ruby-position","under"),g.vh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.pe("DIV"):g.pe("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.vh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.vh(f,"display","none"),f=f.nextElementSibling,g.vh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.vh(k.lastElementChild,"display","none"),d?(g.vh(k,"padding-top","0.6em"),g.vh(f,"top","0")):(g.vh(k,"padding-bottom","0.6em"),g.vh(f,"bottom","0")));return k},h4=function(){g.A.apply(this,arguments)},i4=function(a){h4.call(this);
this.A={};this.H={};this.J={};this.B="_"+T3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},j4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},k4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},l4=function(a,b){var c=j4(a,b);
return void 0!=c?c:null},n4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return m4.test(c),c},gta=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.J[d]:a.C);d=l4(b,"mh");null!=d&&(c.rj=d);d=l4(b,"ju");null!=d&&(c.textAlign=d);d=l4(b,"pd");null!=d&&(c.Ud=d);d=l4(b,"sd");null!=d&&(c.ru=d);d=n4(b,"wfc");null!=d&&(c.windowColor=d);d=j4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},hta=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.H[d]);d=l4(b,"ap");null!=d&&(c.Nf=d);d=j4(b,"cc");null!=d&&(c.Kg=d);d=j4(b,"ah");null!=d&&(c.Ue=d);d=j4(b,"rc");null!=d&&(c.yg=d);d=j4(b,"av");null!=d&&(c.zg=d);return c},ita=function(a,b,c,d){var e={};
g.Ta(e,hta(a,b));g.Ta(e,gta(a,b));d?g.Qb(e,a.C)?(d=a.B,e=a.C):d="_"+T3++:d=b.getAttribute("id")||"_"+T3++;a=j4(b,"t")+c;b=j4(b,"d")||0x8000000000000;if(2==e.Ud||3==e.Ud)c=e.yg,e.yg=e.Kg,e.Kg=c;return new R3(a,b,0,d,e)},o4=function(a){h4.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},p4=function(a){a=g.Od(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},jta=function(a,b,c,d,e){0==d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.yg=a);b=b.ccColCount;void 0!=b&&(f.Kg=b);if(2===f.Ud||3===f.Ud)b=f.yg,f.yg=f.Kg,f.Kg=b;return new R3(c,d,0,e,f)},q4=function(a,b,c,d,e,f,k){U3.call(this,a,b,c,d,e,f,k);
this.type=1},r4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},s4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},t4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},u4=function(a,b){h4.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new W3;this.o.w=1<<this.track},v4=function(a){if("string"===typeof a)return!1;
a=new r4(a,8,0);return kta(a)},kta=function(a){if(!(a.o<a.u.byteLength)||1380139777!=t4(a))return!1;
a.version=s4(a);if(1<a.version)return!1;s4(a);s4(a);s4(a);return!0},w4=function(a,b,c,d,e,f,k){U3.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.H=this.da=0;this.O=NaN;this.ya=0;this.Ba=null;this.ea=new g.I(this.UM,433,this);g.C(this,this.ea);g.vh(this.element,"overflow","hidden")},lta=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},mta=function(a){if(isNaN(a.O)){var b=a.u.Kg;
if(b){var c=g.pe("SPAN");g.ye(c,"\u2013".repeat(b));g.vh(c,Nsa(a,a.u.Db));a.B.appendChild(c);a.O=c.offsetWidth;a.B.removeChild(c)}else a.O=0}return a.O},nta=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.ru&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},ota=function(a){a.G=[].concat(g.na(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.yg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.J=Math.max(mta(a),a.ya,lta(a,a.B))},pta=function(a,b){ota(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.Cn(a.ea));g.vh(a.B,"transform",nta(a,c));a.da=c}ota(a)},x4=function(){h4.call(this)},qta=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Te=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new Q3(b,c,d,e.id,p.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(p),S3(e,p);else{var t={};g.Ta(t,l);qta(a,b,c,d,e,!0,p,t,m)}}},y4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},rta=function(a,b,c,d){d=Object.assign({rj:0},d);
return new R3(a,b,c,"_"+T3++,d)},z4=function(a){g.A.call(this);
this.u=a;this.o=null},tta=function(a){var b={};
if(a=H3(a))b.lang=a,sta.test(a)&&(b.Ud=1);return b},C4=function(a){g.gM.call(this,a);
this.w=a.N();this.T=a.getVideoData();this.ya=g.wL(a);this.U=a;var b=null,c=g.so("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.ao(c));this.ca=b;this.A={Db:{}};this.C={Db:{}};this.J=[];this.O={};this.Z={};this.P=!1;this.sa=g.iM(this.T,this.U);this.za=!!this.T.captionTracks.length;this.Ba=!!this.T.lk;this.ga="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.mm());this.xa=!(!b||!b.Ii());this.B=this.ga&&c&&!this.sa;this.H=!this.B&&this.ga&&this.xa&&this.sa;this.u=this.F=this.G=this.V=this.na=
null;this.da=new z4(this.w);g.C(this,this.da);c=b=this.o=null;this.B||(b=new g.yn(this.BC,void 0,this),g.C(this,b),c=new g.I(this.vO,2E3,this),g.C(this,c));this.ea=b;this.ra=c;this.S=new g.O(this);g.C(this,this.S);this.B||this.S.L(a,"resize",this.Du);this.S.L(a,"onPlaybackAudioChange",this.zK);this.S.L(a,g.YD("captions"),this.gH,this);this.S.L(a,"crx_captions",this.hH,this);A4(this,B4(this,"display-settings")||{})},D4=function(a){if(1==a.w.Jg||1==a.T.Jg||"alwayson"==g.IB(a.T,"yt:cc"))return!0;
if(2==a.w.Jg){var b=B4(a,"module-enabled");if(null!=b)return!!b}if(a.T.captionTracks.length)var c=a.player.getAudioTrack().zq;return"ON"==c||"on"==g.IB(a.T,"yt:cc")},E4=function(a,b){if(a.o&&(void 0===b||!b)||!a.T.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.xn||"FORCED_ON"==c.zq},G4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ba?!1:a.za?!1:!0);c=I3(a.u.u,c);for(var d=[a.T.captionsLanguagePreference,a.w.captionsLanguagePreference,g.IB(a.T,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(H3(c[f])==d[e])return c[f];return a.F&&a.F.Kq?a.F.Kq:(d=c.find(function(k){return k.isDefault}))?d:c[0]||F4(a)}return null},F4=function(a){return a.F&&a.F.xn},H4=function(a){var b=F4(a);
return!!b&&a.o==b},uta=function(a,b){for(var c=a.U.app.B.ib().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},J4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&I4(a,"module-enabled",!!b));a.o=b;E4(a)&&(a.o=F4(a));a.load()},vta=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ya.getPlayerSize();switch(null!=b.params.rj?b.params.rj:1<b.o.length?1:0){case 1:return new q4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new w4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new U3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},A4=function(a,b,c){c=void 0===c?!1:c;
var d=K4.Db;a.A={};g.Ta(a.A,K4);a.A.Db={};g.Ta(a.A.Db,d);a.C={Db:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;m4.test(f);e.Db.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;m4.test(f);e.Db.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||K4.windowColor;m4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Db.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Db.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Te?3:d.bold?1:d.Te?2:0);f=f.Db;switch(e){case 1:f.bold=!0;delete f.Te;break;case 2:delete f.bold;f.Te=!0;break;case 3:f.bold=!0;f.Te=!0;break;default:delete f.bold,delete f.Te}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Db.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=K4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.A;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Db.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Db.fontFamily=f;a.loaded&&a.Du();c&&I4(a,"display-settings",b)},xta=function(a,b){if(b&&!a.G){var c=Ksa({Ud:0,
lang:"en"});a.G=[c,new Q3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.NL(a.player,a.G)}else!b&&a.G&&(wta(a,a.G),a.G=null)},wta=function(a,b){g.VT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.gb(this.J,c)},a);
g.zn(a.ea)},B4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},I4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.oC.prototype.mk=g.ca(12,function(){for(var a=g.be(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ue(a[b])});
g.GR.prototype.mk=g.ca(11,function(){this.o.mk()});
g.oC.prototype.mm=g.ca(10,function(){return!!this.o.textTracks});
g.GR.prototype.mm=g.ca(9,function(){return this.o.mm()});
g.oC.prototype.hk=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.GR.prototype.hk=g.ca(7,function(a){this.o.hk(a)});
g.fC.prototype.Ii=g.ca(6,function(){});
g.oC.prototype.Ii=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.GR.prototype.Ii=g.ca(4,function(){return this.o.Ii()});
g.qz.prototype.Bs=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
g.pt.prototype.Kn=g.ca(1,function(a){return(a=this.Vf(a))?a.o:0});
g.Jy.prototype.Kn=g.ca(0,function(){return 0});
var sta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,m4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(K3,g.A);K3.prototype.mB=function(){return!1};
K3.prototype.Y=function(){this.Ah();g.A.prototype.Y.call(this)};
g.r(L3,K3);L3.prototype.qs=function(a,b,c){b=this.Ik(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Ah();this.o=g.yq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
L3.prototype.rs=function(a){if(this.w)for(var b=g.q(this.w.captionTracks),c=b.next();!c.done;c=b.next())J3(this.u,c.value);a()};
L3.prototype.Ik=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.il()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=H3(a));return g.iq(c,d)};
L3.prototype.Ah=function(){this.o&&this.o.abort()};
M3.prototype.contains=function(a){a=g.rb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
M3.prototype.length=function(){return this.segments.length/2};
g.r(N3,g.A);g.h=N3.prototype;g.h.Y=function(){g.A.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.rz=function(){Fsa(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new M3;this.u&&(this.u.cancel(),this.u=null)};
g.h.yy=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.sg(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.uj(a),a.o[0].duration?(this.B.contains(a.o[0].u)||Gsa(this,a),this.o=g.Xa(a.o)):!g.Q(this.O.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.Bb()<this.w.getCurrentTime()&&Fsa(this,this.w.getCurrentTime()));this.G.start()};
g.h.PM=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Oy(a);c?(a=g.qy(this.A,this.J,{}),b=this.A,g.my(b.u,a,c),b.requestId=a.get("req_id"),Gsa(this,this.A)):(b||null===this.F||(c=this.A.o[0],this.C?this.F(a.response,1E3*(c.startTime+this.w.Bb())):this.F(a.responseText,1E3*(c.startTime+this.w.Bb()))),this.u=this.A=null)};
g.r(O3,K3);g.h=O3.prototype;g.h.qs=function(a,b,c){this.Ah();b=Isa(this,a.getId());b||(b=a.u,b=this.o.u?Jsa(this,b,"386"):Jsa(this,b));if(b){var d=1E3*(b.index.Kn(b.index.Pe())-b.index.Yc(b.index.Pe()));this.w=new N3(new g.hy,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.ev(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.mB=function(){var a=this.A;this.A=!1;return a};
g.h.rs=function(a){var b;this.C?b=[new g.qz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.qz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?Hsa(this,"386"):Hsa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())J3(this.u,c.value);a()};
g.h.Ah=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Ik=function(){return""};
g.r(P3,K3);P3.prototype.qs=function(a,b,c){b=this.Ik(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Ah();this.o=g.yq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
P3.prototype.rs=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.iq(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
J3(this.u,new g.qz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Ah();this.o=g.yq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
P3.prototype.Ik=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=H3(a));return c=g.iq(c,d)};
P3.prototype.Ah=function(){this.o&&this.o.abort()};var Msa=["left","right","center","justify"];var K4={windowColor:"#080808",windowOpacity:0,textAlign:2,Nf:7,Ue:50,zg:100,Db:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(Q3,g.VD);Q3.prototype.toString=function(){return g.VD.prototype.toString.call(this)};g.r(R3,g.VD);R3.prototype.toString=function(){return g.VD.prototype.toString.call(this)};
var T3=0;g.r(U3,g.V);g.h=U3.prototype;g.h.vI=function(a,b){var c=g.Mh(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.uI=function(a,b){var c=g.Ph(this.element),d=a-this.na-.02*this.Ja,e=b-this.sa-.02*this.Ha,f=(d+c.width/2)/this.ca*3;f=Math.floor(g.Od(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Od(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ca;d=100*g.Od(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Od(c,0,1);this.w.params.Nf=l;this.w.params.zg=c;this.w.params.Ue=d;this.u.Nf=l;this.u.zg=c;this.u.Ue=d;this.LB()};
g.h.tI=function(){g.Nn(this.element,"ytp-dragging")};
g.h.LB=function(){this.Ci(this.C)};
g.h.Ci=function(a){var b=Math.min(this.hx(),this.ca),c=this.gx(),d="";3==this.w.params.Ud&&(d="rotate(180deg)");g.vh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.oq(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Ue+2;d=this.u.Nf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.zg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.vh(this.element,a)};
g.h.oq=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.S||this.C.length>b)b=0,this.S=!1,this.C=[],this.F=this.V=this.U=null,g.se(this.B);for(;b<a.length;b++)Qsa(this,a[b])};
g.h.hx=function(){return 0};
g.h.gx=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};Rsa.prototype.B=function(){};W3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
W3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Ssa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];X3.prototype.set=function(a){this.o=a};
X3.prototype.get=function(){return this.o};
Y3.prototype.clear=function(){this.o=0};
Y3.prototype.update=function(){this.o=2==this.o?1:0};
Y3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
Z3.prototype.Mg=function(a){this.pe=a.pe;this.timestamp=a.timestamp};
Z3.prototype.reset=function(){this.timestamp=this.pe=0};
$3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
$3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.pe?a+"_":a+String.fromCharCode(d.pe)}a+="\n"}return a};
$3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Xsa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ysa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Zsa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],$sa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];f4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
V3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(h4,g.A);h4.prototype.reset=function(){};g.r(i4,h4);i4.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
i4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ta(l,this.A[m]);m=k4(c,"b");null!=m&&(l.bold=
m);m=k4(c,"i");null!=m&&(l.Te=m);m=k4(c,"u");null!=m&&(l.underline=m);m=l4(c,"et");null!=m&&(l.charEdgeStyle=m);m=l4(c,"of");null!=m&&(l.offset=m);m=n4(c,"bc");null!=m&&(l.background=m);m=n4(c,"ec");null!=m&&(l.Cq=m);m=n4(c,"fc");null!=m&&(l.color=m);m=l4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=j4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=j4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=j4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=l4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Nb=10<m?m-1:m);
c=l4(c,"hg");null!=c&&(l.Sx=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=gta(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=hta(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=ita(this,d,e,!1);g.C(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;
m=!!k4(d,"a");n=(j4(d,"t")||0)+n;var p=j4(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.na(d.childNodes));z.length&&(this.F=null!=d.getAttribute("d"));for(var B=0;B<z.length;B++){var D=z[B],E=void 0;0<B&&(m=!0);var G=void 0;1==D.nodeType&&(G=D);if(G&&"s"==G.tagName){if((D=this.A[G.getAttribute("p")])&&D.Nb&&(1==D.Nb?(D=z.slice(B,B+4),4==D.length&&(E=fta(n,p,l,m,
t,D,this.A),B+=3)):E=fta(n,p,l,m,t,[G],this.A)),!E){var F=G;E=n;G=p;D=l;var ka=m,pa=t,bc=F.textContent?F.textContent:"",Kc=this.A[F.getAttribute("p")];F=j4(F,"t")||0;E=new Q3(E+F,G-F,pa,D,bc,ka,Kc)}}else E=new Q3(n,p,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId==this.B&&(this.o=ita(this,d,e,!0),g.C(this,this.o),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,S3(this.o,k),c.push(k)}e=c}else e=[];return e};var yta=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(o4,h4);o4.prototype.reset=function(){this.u.clear()};
o4.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Te=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!=f.ecEdgeColor&&(k.Cq=p4(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!=
f.fcForeColor&&(k.color=p4(f.fcForeColor));void 0!=f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!=f.bcBackColor&&(k.background=p4(f.bcBackColor));void 0!=f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Nb=10<l?l-1:l,k.af=yta.get(k.Nb));f.hgHorizGroup&&(k.Sx=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=
f.mhModeHint&&(k.rj=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Ud=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.ru=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=p4(f.wfcWinFillColor)),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.Ue=f.ahHorPos),
void 0!=f.apPoint&&(l.Nf=f.apPoint),void 0!=f.avVerPos&&(l.zg=f.avVerPos),void 0!=f.ccCols&&(l.Kg=f.ccCols),void 0!=f.rcRows&&(l.yg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=jta(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+T3++,l=jta(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,p=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],B=z.utf8;if(B){var D=z.tOffsetMs||0,E=null;z.pPenId&&(E=this.o.get(z.pPenId));if(2===(null!=l.params.rj?l.params.rj:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(z=E&&1===E.Nb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var G=t[z+1].pPenId;(G=this.o.get(G))&&G.Nb&&2==G.Nb?(G=t[z+2].pPenId,G=this.o.get(G),!G||!G.Nb||3>G.Nb?z=!1:(G=t[z+3].pPenId,z=(G=this.o.get(G))&&G.Nb&&2==G.Nb?!0:
!1)):z=!1}if(z){D=t[m+1].utf8;z=t[m+3].utf8;G=t[m+2].utf8;var F=this.o.get(t[m+2].pPenId);B=eta(B,D,G,z,F);n=new Q3(e,f,p,k,B,n,E);m+=3}else n=new Q3(e+D,f-D,p,l.id,B,n,E||u);n&&(d.push(n),S3(l,n))}n=!0}}}else d=[];return d};g.r(q4,U3);q4.prototype.oq=function(a){var b=this.w.o;U3.prototype.oq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,zta);var e=c.o;var f=d}Qsa(this,c,d)}};
var zta={XF:!0};g.r(r4,Rsa);r4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+T3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new R3(c,d-c,5,f,{textAlign:0,Nf:0,Ue:2.5*b,zg:5.33*a});e=new Q3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(u4,h4);u4.prototype.w=function(a){a=new r4(a,a.byteLength,this.u);if(kta(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=t4(a)*(1E3/45):1==a.version&&(a.A=4294967296*t4(a)+t4(a)),a.C=s4(a);0<a.C;a.C--){var b=s4(a),c=s4(a),d=s4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,hw:c,iw:d,order:b.o.length}))}Wsa(this.o,a);return a.w}return[]};
u4.prototype.reset=function(){this.o.clear()};g.r(w4,U3);g.h=w4.prototype;g.h.LB=function(){g.Dn(this.ea)};
g.h.UM=function(){g.Nn(this.element,"ytp-rollup-mode");this.Ci(this.Ba,!0)};
g.h.gx=function(){return this.A?this.J:this.H};
g.h.hx=function(){return this.A?this.H:this.J};
g.h.Ci=function(a,b){this.Ba=a;if(this.w.params.yg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.J;this.H=this.J=0;U3.prototype.Ci.call(this,a);pta(this,b);U3.prototype.Ci.call(this,a)}else U3.prototype.Ci.call(this,a)};g.r(x4,h4);
x4.prototype.w=function(a,b){for(var c=[],d=a.split(Ata),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Bta.test(f)){var l=L4.exec(f);if(l&&4<=l.length){var m=y4(l[1]),n=y4(l[2])-m;m+=k;var p,t=p=void 0,u=void 0,z=void 0,B=(l=l[3])?l.split(" "):[];l={textAlign:2};B=g.q(B);for(var D=B.next();!D.done;D=B.next())if(D=D.value.split(":"),2==D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(z=D[0],l.zg=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=E.split(",");
t=D[0];l.Ue=Number.parseInt(t,10);2==D.length&&(p=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.zg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Ue=0;break;case 1:l.Ue=100;break;default:l.Ue=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Nf=0>t||8<t?7:t;p=l;f=f.substring(L4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=rta(m,n,5,t),n=new Q3(m,n,5,k.id,p,!1,g.Ob(f)?void 0:f),c.push(k),c.push(n),S3(k,n);else for(u=p.split(Cta),1==u.length?(p=5,t=rta(m,n,p,t)):(z=p=6,t=Object.assign({Kg:32},t),t=new R3(m,n,z,"_"+T3++,t)),c.push(t),z=m,l=0;l<u.length;l++)B=u[l],0==l%2?(D=g.Q1("<html>"+B+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(B))):E=D.firstChild,qta(this,z,n-(z-m),p,t,0<l,E,f,c)):z=y4(B)+k}L4.lastIndex=0}}return c};
var Bta=/^NOTE/,Ata=/(?:\r\n|\r|\n){2,}/,L4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Cta=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(z4,g.A);z4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
z4.prototype.reset=function(){this.o&&this.o.reset()};
z4.prototype.Y=function(){this.clear();g.A.prototype.Y.call(this)};g.r(C4,g.gM);g.h=C4.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.U.app.B;a&&!a.la()&&a.mk()}else xta(this,!1);g.gM.prototype.Y.call(this)};
g.h.load=function(){g.gM.prototype.load.call(this);var a=!g.Q(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?uta(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.qs(this.o,"json3",(0,g.x)(this.DN,this)),!a||this.B||this.H||H4(this)||this.player.ma("captionschanged",G3(this.o))),a||(this.o&&!H4(this)?this.player.ma("captionschanged",G3(this.o)):this.player.ma("onCaptionsTrackListChanged"));
else{var b;this.sa?b=new O3(this.T.ka,this.player):this.za?b=new L3(this.w,this.T,this.player.getAudioTrack()):b=new P3(this.T.lk,this.T.videoId,this.T.captionsLanguagePreference||this.w.captionsLanguagePreference||g.IB(this.T,"yt:cc_default_lang")||this.w.oc,this.T.xq,this.w);this.u=b;g.C(this,this.u);b.rs((0,g.x)(this.CN,this))}};
g.h.unload=function(){this.B&&this.o?uta(this,!1):(this.ra&&g.En(this.ra),g.iR(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Ah(),this.da.clear(),this.G&&g.NL(this.player,this.G),this.Du());g.gM.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.LI(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ga?this.B||this.H:E4(this)||D4(this))&&this.load()};
g.h.CN=function(){var a;this.P||D4(this)?a=G4(this,this.P):E4(this)&&(a=F4(this));if(this.B||this.H){for(var b=I3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.rz(e),srclang:H3(e),id:e.toString()};this.H||(f.src=this.u.Ik(e,"vtt"));e==a&&(f["default"]=1);c.push(g.oe("TRACK",f))}a=this.U.app.B;a.hk(c);c=a.ib();this.xa&&this.S.L(c.textTracks,"change",this.EN)}else!this.o&&a&&J4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.EN=function(){for(var a=this.U.app.B.ib().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=I3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&J4(this,b,!0)};
g.h.mP=function(){!this.o&&this.B||this.unload()};
g.h.DN=function(a,b,c,d){if(a){this.u.mB()&&(this.J=[],g.iR(this.U.app,"captions",void 0),g.zn(this.ea),this.da.reset());var e=this.da;c=c||0;d=d||0;if(e.u.fa("html5_disable_rawcc_killswitch")){if("string"!==typeof a){var f=new DataView(a);8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Qt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),v4(a)||(a=Dsa(new Uint8Array(a))))}}else"string"===typeof a||v4(a)||(f=new DataView(a),a=8>=f.byteLength||1718909296!==f.getUint32(4)?"":(f=g.Qt(f,0,
1835295092))&&f.size?Dsa(new Uint8Array(a.slice(f.dataOffset,f.dataOffset+f.size))):"");if(a)try{if("string"!==typeof a){var k=a,l=c,m=d;if(!v4(k))throw Error("Invalid binary caption track data");e.o||(e.o=new u4(m,b));var n=e.o.w(k,l)}else{if("WEBVTT"==a.substring(0,6))b=a,m=c,e.o||(e.o=new x4),l=e.o.w(b,m),.01>Math.random()&&g.Ko(Error("Deprecated subtitles format in web player: WebVTT")),k=l;else b:{l=a;if("{"===l[0])try{e.o||(e.o=new o4(tta(b)));k=e.o.w(l,c);break b}catch(D){g.M(D);k=[];break b}m=
g.Q1(l);if(!m||!m.firstChild){var p=Error("Invalid caption track data");p.params=l;throw p;}if("timedtext"==m.firstChild.tagName){if(3==parseInt(m.firstChild.getAttribute("format"),10)){e.o||(e.o=new i4(tta(b),e.u));k=e.o.w(m,c);break b}var t=Error("Unsupported subtitles format in web player (Format2)");t.params=l;throw t;}if("transcript"==m.firstChild.tagName){var u=Error("Unsupported subtitles format in web player (Format1)");u.params=l;throw u;}var z=Error("Invalid caption track data");z.params=
l;throw z;}n=k}var B=n}catch(D){g.M(D),e.clear(),B=[]}else B=[];g.NL(this.player,B);!this.P||this.H||H4(this)||g.Kx(this.w)||g.Lx(this.w)||(g.En(this.ra),B=Ksa({Nf:0,Ue:5,zg:5,yg:2,textAlign:0,Ud:0,lang:"en"}),this.V=[B],e=["Click "," for settings"],this.na||(n=new g.DC(g.$M()),g.C(this,n),this.na=n.element),n=B.end-B.start,(b=g.rz(this.o))&&this.V.push(new Q3(B.start,n,0,B.id,b)),this.V.push(new Q3(B.start,n,0,B.id,e[0]),new Q3(B.start,n,0,B.id,this.na,!0),new Q3(B.start,n,0,B.id,e[1],!0)),g.NL(this.player,
this.V),g.Cn(this.ra));!this.P||this.H||H4(this)||(I4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(B=g.U(this.player.app))&&g.LI(B.B));this.P=!1}};
g.h.gH=function(a){this.J.push(a);g.zn(this.ea)};
g.h.hH=function(a){g.gb(this.J,a);this.u instanceof O3&&this.u.C&&g.VT(this.player.app,[a],void 0);g.zn(this.ea)};
g.h.nO=function(a){if(a instanceof R3){var b=this.O[a.id];b&&b.w!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=vta(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.vO=function(){wta(this,this.V);this.V=null};
g.h.BC=function(){this.ea.stop();g.Pb(this.Z);this.J.sort(g.XD);var a=this.J;if(this.G){var b=(0,g.ve)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.nO,this);g.Bb(this.O,function(c,d){this.Z[d]?(c.element.parentNode||g.RL(this.player,c.element,4),c.Ci(this.Z[d])):(c.dispose(),delete this.O[d])},this)};
g.h.CO=function(){A4(this,{},!0);g.Q(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.lF=function(){var a=K4.Db;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Te?3:a.bold?1:a.Te?2:0,textOpacity:a.textOpacity,windowColor:K4.windowColor,windowOpacity:K4.windowOpacity};var b=B4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.HC=function(a,b){b=void 0===b?!1:b;var c={};g.Ta(c,B4(this,"display-settings"));g.Ta(c,a);A4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Du=function(){!this.B&&this.loaded&&(g.Bb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.BC())};
g.h.Lc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Od(b,-2,4);this.HC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&J4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.Eb&&I4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Pa(b))break;if(g.Ob(b)){J4(this,null,!0);break}for(var d=I3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?Csa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||J4(this,c,!0)}else return this.loaded&&this.o&&!H4(this)?G3(this.o):{};return"";case "tracklist":return this.u?(0,g.Fc)(I3(this.u.u,!(!b||!b.includeAsr)),function(k){return G3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||xta(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.Eb&&a.push("stickyLoading");return a};
g.h.IG=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.eP=function(){this.loaded&&this.o&&!H4(this)?(I4(this,"module-enabled",!1),this.unload(),E4(this,!0)&&J4(this,F4(this),!1)):J4(this,H4(this)||!this.o?G4(this,!0):this.o,!0)};
g.h.zK=function(){var a=H4(this);E4(this,a)?J4(this,this.player.getAudioTrack().xn,!1):this.T.captionTracks.length&&(this.loaded&&this.unload(),(this.ga?this.B||this.H:E4(this)||D4(this))&&(a?J4(this,G4(this),!1):this.load()))};g.vM.captions=C4;})(_yt_player);
